---
- name: Create rsa key pair and save private key into a file
  amazon.aws.ec2_key:
    region: "{{ region }}" 
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: project4-key
    key_type: rsa
    file_name: /root/project4-key.pem
  when: state == "create"

- name: Set permissions on the private key file
  ansible.builtin.file:
    path: /root/project4-key.pem
    mode: '0600'
  when: state == "create"

- name: remove key pair from AWS by name
  amazon.aws.ec2_key:
    region: "{{ region }}" 
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: project4-key
    state: absent
  when: state == "delete"
