---
- name: msg   # project4-vpc의 정보를 조회하는 메시지 출력
  debug:
    msg: "VPC 정보를 가져오는 중입니다."

- name: Get VPC ID by name   # project4-vpc의 정보를 조회합니다.
  amazon.aws.ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: vpc_info
  when: state == "create"

- name: msg   # HTTPS 보안 그룹 생성을 시작하는 메시지 출력
  debug:
    msg: "HTTPS 보안 그룹 생성 시작합니다."
  when: state == "create"

- name: Create security group   # HTTPS용 보안 그룹 생성 (프로토콜 TCP, 포트 443 허용)
  amazon.aws.ec2_security_group:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: "{{ sg_name }}"
    description: "{{ sg_description }}"
    vpc_id: "{{ vpc_info.vpcs[0].id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp        # 프로토콜 TCP 사용
        from_port: 443    # 포트 443 (HTTPS)
        to_port: 443
        cidr_ip: 0.0.0.0/0  # 모든 IP 허용
    state: present
  register: sg_result
  when: state == "create"

- name: Tag the security group with Name = sg_name    # 생성한 보안 그룹에 Name 태그 추가
  amazon.aws.ec2_tag:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    resource: "{{ sg_result.group_id }}"  # 생성된 보안 그룹의 group_id
    tags:
      Name: "{{ sg_name }}"
  when: state == "create"

- name: msg   # HTTPS 보안 그룹 삭제 메세지
  debug:
    msg: "HTTPS 보안 그룹 삭제 시작합니다."
  when: state == "delete"

- name: Find security group by name  # 이름으로 보안 그룹 조회
  amazon.aws.ec2_security_group_info:
    region: "{{ region }}"
    filters:
      group-name: "{{ sg_name }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: sg_result
  when: state == "delete"

- name: Delete security group   # 보안 그룹 삭제
  amazon.aws.ec2_security_group:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    state: absent
    group_id: "{{ sg_result.security_groups[0].group_id }}"
  when:
    - state == "delete"
    - sg_result.security_groups | length > 0
