---
- block:
    - name: AMI 정보 조회
      amazon.aws.ec2_ami_info:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        filters:
          "tag:Name": "project4-ami"
      register: ami_info

    - name: Create Launch Template from AMI
      amazon.aws.ec2_launch_template:
        name: "project4-launch-template"
        image_id: "{{ ami_info.images[0].image_id }}"
        instance_type: t2.micro
        key_name: "{{ key_name }}"
        network_interfaces:
          - device_index: 0
            associate_public_ip_address: false
            subnet_id: "{{ subnet_private1_id }}"
            groups: "{{ security_groups }}"
        iam_instance_profile: project4-code-deploy-ec2-role
        tags:
          Name: project4-launch-template
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: present
      register: launch_template_info
  when: state == "create"

- block:
    - name: Delete Launch Template
      amazon.aws.ec2_launch_template:
        name: "project4-launch-template"
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: absent
      register: delete_template_result
  when: state == "delete"

