- block:
    - name: 퍼블릭 서브넷 1 ID 조회
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "project4-subnet-public1-ap-northeast-2a"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: public_subnet1_info

    - name: 퍼블릭 서브넷 2 ID 조회
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "project4-subnet-public2-ap-northeast-2c"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: public_subnet2_info

    - name: 프라이빗 서브넷 1 ID 조회
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "project4-subnet-private1-ap-northeast-2a"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: private_subnet1_info

    - name: 프라이빗 서브넷 2 ID 조회
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "project4-subnet-private2-ap-northeast-2c"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: private_subnet2_info

    - name: IGW ID 조회
      amazon.aws.ec2_vpc_igw_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "project4-igw"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: igw_info

    - name: NAT Gateway 1 ID 조회
      amazon.aws.ec2_vpc_nat_gateway_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "project4-natgw"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: natgw1_info

    - name: Debug public subnet 1 info
      debug:
        var: public_subnet1_info

    - name: Debug IGW info
      debug:
        var: igw_info

    - name: Debug NAT Gateway 1 info
      debug:
        var: natgw1_info

        

    - name: 퍼블릭 라우팅 테이블 생성 및 서브넷 연결
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: project4-public-rtb
        subnets:
          - "{{ public_subnet1_info.subnets[0].id }}"
          - "{{ public_subnet2_info.subnets[0].id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_info.internet_gateways[0].internet_gateway_id }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"

    - name: 프라이빗1 라우팅 테이블 생성 및 서브넷 연결
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: project4-private1-rtb
        subnets:
          - "{{ private_subnet1_info.subnets[0].id }}"
        routes:
          - dest: 0.0.0.0/0
            nat_gateway_id: "{{ natgw1_info.result[0].nat_gateway_id }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"

    - name: 프라이빗2 라우팅 테이블 생성 및 서브넷 연결
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: project4-private2-rtb
        subnets:
          - "{{ private_subnet2_info.subnets[0].id }}"
        routes:
          - dest: 0.0.0.0/0
            nat_gateway_id: "{{ natgw1_info.result[0].nat_gateway_id }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
     
  when: state == "create"

- block:
    - name: 프라이빗1 라우팅 테이블 정보 조회
      amazon.aws.ec2_vpc_route_table_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "project4-private1-rtb"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: private1_rtb_info

    - name: 연결된 서브넷 ID 리스트 추출
      set_fact:
        private1_rtb_subnet_ids: >-
          {{ private1_rtb_info.route_tables[0].associations
             | selectattr('subnet_id', 'defined')
             | map(attribute='subnet_id')
             | list }}
      when:
        - private1_rtb_info.route_tables is defined
        - private1_rtb_info.route_tables | length > 0

    - name: 프라이빗1 라우팅 테이블에서 서브넷 연결 해제
      amazon.aws.ec2_vpc_route_table:
        route_table_id: "{{ private1_rtb_info.route_tables[0].id }}"
        subnets: []
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        lookup: id
      when:
        - private1_rtb_info.route_tables is defined
        - private1_rtb_info.route_tables | length > 0
        - private1_rtb_subnet_ids | length > 0

    - name: 프라이빗1 라우팅 테이블 삭제
      amazon.aws.ec2_vpc_route_table:
        route_table_id: "{{ private1_rtb_info.route_tables[0].id }}"
        region: "{{ region }}"
        state: absent
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        lookup: id
      when:
        - private1_rtb_info.route_tables is defined
        - private1_rtb_info.route_tables | length > 0
  when: state == "delete"

